---
name: Devel-Graph
version: 0.08
version_from: lib/Devel/Graph.pm
license: gpl
distribution_type: module
generated_by: Devel-Graph version 0.08
installdirs: site
requires:
  Graph::Flowchart: 0.09
  PPI: 1.109
