--- #YAML:1.0
name: Devel-Graph
version: 0.05
version_from: lib/Devel/Graph.pm
license: gpl
distribution_type: module
generated_by: Devel-Graph version 0.05
installdirs: site
requires:
  Graph::Flowchart: 0.06
  PPI: 1.108
