---
abstract: Turn Perl code into a graphical flowchart
author:
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  Test::Differences: 0.47
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.68
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Graph
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Graph::Easy: 0.60
  Graph::Flowchart: 0.10
  PPI: 1.201
  Scalar::Util: 1.19
  perl: 5.8.1
version: 0.12
