--- #YAML:1.0
name: Devel-Graph
version: 0.07
version_from: lib/Devel/Graph.pm
license: gpl
distribution_type: module
generated_by: Devel-Graph version 0.07
installdirs: site
requires:
  Graph::Flowchart: 0.07
  PPI: 1.109
