--- 
abstract: Turn Perl code into a graphical flowchart
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::Differences: 0.47
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: gpl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Graph
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Graph::Flowchart: 0.1
  PPI: 1.118
  Scalar::Util: 1.13
version: 0.11
