--- #YAML:1.0
name: Devel-Graph
version: 0.02
version_from: lib/Devel/Graph.pm
license: gpl
distribution_type: module
generated_by: Devel-Graph version 0.02
installdirs: site
requires:
  Graph::Easy: 0.32
  PPI: 1.103
